# Generated by Django 4.2.2 on 2023-06-16 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='nam',
        ),
    ]
