# Generated by Django 4.2.2 on 2023-06-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_name_owner_nam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='owner',
        ),
    ]
